[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

# Mantle network chain IDs
# Mantle Mainnet: 5000
# Mantle Sepolia (Testnet): 5003

[rpc_endpoints]
mantle = "${MANTLE_RPC_URL}"
mantle-sepolia = "${MANTLE_SEPOLIA_RPC_URL}"

[etherscan]
mantle = { key = "${MANTLESCAN_API_KEY}", url = "https://explorer.mantle.xyz/api", chain = 5000 }
mantle-sepolia = { key = "${MANTLESCAN_API_KEY}", url = "https://explorer.sepolia.mantle.xyz/api", chain = 5003 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
